theme = "transparent"

[editor]
line-number = "relative"
mouse = false
scrolloff = 12
cursorline = true
idle-timeout = 0
completion-timeout = 0
completion-trigger-len = 1
bufferline = "multiple"
popup-border = "all"
rulers = [80]
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = false

[keys.normal]
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"
"C-k" = "jump_view_up"
"C-j" = "jump_view_down"
